[[plugins]]
package = "netlify-plugin-no-more-404"

  # all inputs are optional, we just show you the defaults below
  [plugins.inputs]

  # either "warn" or "error"
  on404 = "error"

  # change this key to a new one any time you need to restart from scratch
  cacheKey = "MyCacheKey"

  # (for development) turn true for extra diagnostic logging
  debugMode = false


[[plugins]]
package = "netlify-plugin-hashfiles"
